# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
        exclude: paroxython/resources/spec.md|tests/snapshots/*|tests/data/dummy/*|tests/data/programming_idioms/*
    -   id: end-of-file-fixer
        exclude: docs/.*\.html|tests/snapshots/*|tests/data/dummy_taxons_and_programs\.txt|tests/data/programming_idioms/*
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-json
    -   id: requirements-txt-fixer
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.25.2
    hooks:
    -   id: pyupgrade
        exclude: tests/snapshots/*
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
        exclude: tests/snapshots/*|tests/data/programming_idioms/*|docs/resources/fibonacci.py
        args: [--line-length=100]
